#define HYDRO_MESHLESS_FINITE_MASS 
#define EOS_GAMMA (5.0/3.0)
#define TURB_DIFF_ENERGY 
#define TURB_DIFF_VELOCITY 
#define ADAPTIVE_GRAVSOFT_FORALL 1+2
#define GALSF 
#define GALSF_SFR_CRITERION (0+1+2+4)
#define COOLING 
#define OUTPUT_TEMPERATURE 
#define MERGESPLIT_HARDCODE_MAX_MASS (2.0e-10)
#define MERGESPLIT_HARDCODE_MIN_MASS (2.0e-11)
